"""
Chroma Cloud-backed document ingestion for AbhyasAI.

Each document type (syllabus, pyq, lecture, notes, …) is sharded into its own
Cloud collection so that search is fast and semantically focused.  Collections
are created on-demand with get_or_create_collection + a Schema that enables
hybrid (dense + sparse) search.

Chroma Cloud imposes a 16 KiB-per-document limit; the StructureAwareChunker
already enforces CHUNK_SIZE ≤ 800 chars, which is well within that limit.
"""

import os
import hashlib
from typing import Any, Dict, List, Optional, Tuple, Union

from services.document_service import extract_and_clean_document
from services.rag.chunking import StructureAwareChunker
from services.rag.embeddings import (
    get_cloud_client,
    get_collection_name,
    get_hybrid_schema,
    get_dense_ef,
)
from services.rag.metadata import ChunkMetadata


# Maximum characters per chunk to stay under Chroma Cloud's 16 KiB limit.
# 800 chars ≈ 800 bytes UTF-8 (most educational text is ASCII), well under limit.
_MAX_CHUNK_CHARS = 800


class UniversalIngestionService:
    """
    Universal document ingestion pipeline supporting:
    PDF, TXT, Markdown, DOCX, PPTX, YouTube Transcripts, and Raw Pasted Text.

    Vectors are stored in Chroma Cloud with:
    - Dense embeddings  (Qwen3 0.6B via Chroma Cloud)
    - Sparse embeddings (SPLADE via Chroma Cloud, auto-generated by schema)
    - Metadata sharded by document type for targeted retrieval
    """

    def __init__(self):
        # Cloud client and schema are lazy — not connected until first use
        self._client = None
        self._schema = None
        self.chunker = StructureAwareChunker(
            chunk_size=_MAX_CHUNK_CHARS,
            chunk_overlap=int(os.getenv("CHUNK_OVERLAP", "120")),
        )

    @property
    def client(self):
        if self._client is None:
            self._client = get_cloud_client()
        return self._client

    @property
    def schema(self):
        if self._schema is None:
            self._schema = get_hybrid_schema()
        return self._schema

    def get_or_create_collection(self, collection_type: str):
        """Get or create a Chroma Cloud collection for the given document type."""
        name = get_collection_name(f"abhyas_{collection_type.lower()}")
        return self.client.get_or_create_collection(
            name=name,
            schema=self.schema,
            embedding_function=get_dense_ef(),
        )

    # ------------------------------------------------------------------
    # Hashing helpers
    # ------------------------------------------------------------------

    def compute_hash(self, content: Union[str, bytes]) -> str:
        if isinstance(content, str):
            content = content.encode("utf-8", errors="ignore")
        return hashlib.sha256(content).hexdigest()

    def is_document_ingested(self, collection, document_id: str) -> bool:
        try:
            results = collection.get(where={"document_id": document_id}, limit=1)
            return len(results.get("ids", [])) > 0
        except Exception:
            return False

    # ------------------------------------------------------------------
    # Text extraction
    # ------------------------------------------------------------------

    def extract_text(self, file_source: Any, filename: str) -> str:
        if not filename:
            return file_source.strip() if isinstance(file_source, str) else ""

        ext = os.path.splitext(filename)[1].lower()
        if ext in [".docx", ".doc"]:
            return self._extract_docx(file_source)
        elif ext in [".pptx", ".ppt"]:
            return self._extract_pptx(file_source)
        elif ext in [".pdf", ".txt", ".md", ".csv"]:
            return extract_and_clean_document(file_source, filename)
        else:
            try:
                return extract_and_clean_document(file_source, filename)
            except Exception:
                if hasattr(file_source, "read"):
                    data = file_source.read()
                    return data.decode("utf-8", errors="ignore") if isinstance(data, bytes) else str(data)
                return str(file_source)

    def _extract_docx(self, file_source: Any) -> str:
        try:
            import docx
            doc = docx.Document(file_source)
            return "\n\n".join(p.text for p in doc.paragraphs if p.text.strip())
        except Exception as e:
            print(f"DOCX extraction warning: {e}")
            return ""

    def _extract_pptx(self, file_source: Any) -> str:
        try:
            import pptx
            prs = pptx.Presentation(file_source)
            slides = []
            for i, slide in enumerate(prs.slides, 1):
                texts = [s.text.strip() for s in slide.shapes if hasattr(s, "text") and s.text.strip()]
                if texts:
                    slides.append(f"--- SLIDE {i} ---\n" + "\n".join(texts))
            return "\n\n".join(slides)
        except Exception as e:
            print(f"PPTX extraction warning: {e}")
            return ""

    # ------------------------------------------------------------------
    # Ingestion entry points
    # ------------------------------------------------------------------

    def ingest_document(
        self,
        file_source: Any,
        filename: str,
        document_type: str,
        subject: str = "General",
        year: str = "",
        force_reindex: bool = False,
    ) -> Dict[str, Any]:
        """Universal ingestion entry point."""
        raw_text = self.extract_text(file_source, filename)
        if not raw_text or not raw_text.strip():
            raise ValueError(f"Could not extract meaningful text from {filename or 'source'}.")

        doc_hash = self.compute_hash(raw_text)
        doc_type_clean = document_type.lower()
        target_type = (
            doc_type_clean
            if doc_type_clean in {"syllabus", "pyq", "lecture", "notes", "question", "answer"}
            else "documents"
        )
        collection = self.get_or_create_collection(target_type)

        # Skip if already ingested
        if not force_reindex and self.is_document_ingested(collection, doc_hash):
            existing = collection.get(where={"document_id": doc_hash})
            return {
                "document_id": doc_hash,
                "chunks_created": len(existing.get("ids", [])),
                "collection": collection.name,
                "status": "already_indexed",
                "message": "Document already indexed. Vectors preserved in Chroma Cloud.",
            }

        # Structure-aware chunking
        chunk_tuples: List[Tuple[str, ChunkMetadata]] = self.chunker.chunk_document(
            text=raw_text,
            document_id=doc_hash,
            document_type=doc_type_clean,
            source_name=filename or "Uploaded Document",
            subject=subject,
            year=year,
        )
        if not chunk_tuples:
            raise ValueError("Document produced 0 chunks after chunking.")

        ids       = [meta.chunk_id for _, meta in chunk_tuples]
        documents = [txt for txt, _ in chunk_tuples]
        metadatas = [meta.to_chroma_dict() for _, meta in chunk_tuples]

        # Upsert to Chroma Cloud; schema triggers sparse embedding generation automatically.
        collection.upsert(ids=ids, documents=documents, metadatas=metadatas)

        print(f"[ChromaCloud] Upserted {len(ids)} chunks → '{collection.name}'")
        return {
            "document_id": doc_hash,
            "chunks_created": len(ids),
            "collection": collection.name,
            "status": "success",
            "subject": subject,
            "document_type": doc_type_clean,
        }

    def ingest_youtube_transcript(
        self,
        video_id: str,
        transcript_text: str,
        subject: str = "General",
    ) -> Dict[str, Any]:
        return self.ingest_document(
            file_source=transcript_text,
            filename=f"YouTube Lecture ({video_id})",
            document_type="lecture",
            subject=subject,
        )

    def ingest_raw_text(
        self,
        text: str,
        title: str,
        document_type: str,
        subject: str = "General",
        year: str = "",
    ) -> Dict[str, Any]:
        return self.ingest_document(
            file_source=text,
            filename=title,
            document_type=document_type,
            subject=subject,
            year=year,
        )
